### Numpy code along
Numpy (short for Numerical Python) is used for numeric computing and includes support for multi-dimensional arrays and matrices along with a variety of mathematical functions to apply to them. 

The basic data structures in Numpy are arrays, which can be used to represent tabular data. You can think of arrays as lists of lists, where all the elements of a list are of the same type (typically numeric since the reason you use Numpy is to do numeric computing). A matrix is just a two-dimensional array.

The size of an array is the total number of elements in every list. The shape of an array is the size of the array along each dimension (group, subgroup, rows, columns)

In [1]:
import numpy as np

In [2]:
a = np.random.random((6,3))

In [3]:
print(a)

[[0.25863261 0.29037444 0.23045113]
 [0.6215434  0.88239921 0.08838296]
 [0.38117844 0.61508489 0.55940369]
 [0.73903451 0.02268816 0.42810847]
 [0.66516596 0.14152668 0.67917047]
 [0.4537806  0.43918452 0.03528909]]


In [4]:
a.shape

(6, 3)

In [5]:
a.size

18

#### 3-D arrays
It will create an array with 3 groups of 4x5 matrices (groups, rows, columns)

In [6]:
f = np.random.random((3,4,5))
print(f)

[[[0.89836095 0.29609629 0.80292778 0.29961626 0.17414411]
  [0.62615406 0.76274847 0.40216247 0.84071922 0.60798756]
  [0.32435899 0.64839192 0.09046267 0.49975624 0.26851702]
  [0.04010463 0.10691695 0.87779608 0.15565992 0.0731709 ]]

 [[0.98540219 0.91196259 0.52092403 0.11833242 0.94549908]
  [0.40834637 0.22072044 0.63192318 0.26842969 0.4405589 ]
  [0.33972738 0.58248482 0.31878545 0.04343898 0.69064977]
  [0.81670972 0.16207972 0.66557102 0.05874646 0.96241985]]

 [[0.35176515 0.04158829 0.07035751 0.9140906  0.39938913]
  [0.62886176 0.70798876 0.07269246 0.67608459 0.98425197]
  [0.7588117  0.97790797 0.79283338 0.05645006 0.47725166]
  [0.91680407 0.44627754 0.1927636  0.91201192 0.92346065]]]


__4-D arrays__
It will create 2 groups, of 3 4x3 matrices (groups, sub-groups, rows, columns)

In [7]:
g = np.random.random((2,3,4,5))
print(g)

[[[[0.64477859 0.89641884 0.86355138 0.89418741 0.7422256 ]
   [0.05897595 0.53376983 0.67591669 0.81828168 0.57045207]
   [0.34571598 0.96314    0.38039216 0.50406145 0.12681685]
   [0.16103219 0.17502662 0.75465242 0.18050968 0.9861452 ]]

  [[0.25719552 0.52250463 0.85864575 0.62885899 0.93010446]
   [0.64419896 0.37639589 0.67292751 0.28252162 0.06294175]
   [0.66290859 0.01828023 0.47456788 0.09996702 0.44227327]
   [0.31678042 0.32316412 0.32628916 0.22990484 0.47024849]]

  [[0.60945809 0.85148652 0.24734991 0.852702   0.91857969]
   [0.61141536 0.2614762  0.6357038  0.74227369 0.09065509]
   [0.48025622 0.27108494 0.13860044 0.20101975 0.92120797]
   [0.47618347 0.01892212 0.74914416 0.18879969 0.99420585]]]


 [[[0.06329551 0.84831754 0.45562369 0.38706537 0.92215855]
   [0.7766793  0.61969148 0.23911715 0.82167839 0.63246147]
   [0.17148559 0.75411191 0.55116073 0.38474395 0.72992052]
   [0.40186536 0.18979982 0.9098072  0.55035599 0.0235737 ]]

  [[0.17345782 0.38922583 0.30

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [8]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(lst) # Formula to convert list of lists, to array
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Constant arrays

In [9]:
b = np.zeros((2,2))  # Create an array of all zeros
print(b)

c = np.ones((1,2))   # Create an array of all ones
print(c)

d = np.full((3,2), 7) # Create a constant array: np.full((rows,colums), number)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


#### Random values:

In [10]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.97848268 0.4224495 ]
 [0.87830187 0.64038928]]


### Array indexing
[row index, column index]

- If we want the whole row but only one or some columns, [:,columns]

In [11]:
a[0] #First row of matrix a
a[:,1] #All rows of the second column

array([0.29037444, 0.88239921, 0.61508489, 0.02268816, 0.14152668,
       0.43918452])

In [12]:
a[4,2] # Value in the fifth row and third column of matrix a [row index, column index]

0.6791704711675347

In [13]:
a[0:2,2] # First and second rows, third column

array([0.23045113, 0.08838296])

In [14]:
print(a)

[[0.25863261 0.29037444 0.23045113]
 [0.6215434  0.88239921 0.08838296]
 [0.38117844 0.61508489 0.55940369]
 [0.73903451 0.02268816 0.42810847]
 [0.66516596 0.14152668 0.67917047]
 [0.4537806  0.43918452 0.03528909]]


__Array indexing with 3+ dimensional matrices__

In [41]:
print(g[0]) # First group of array g

[[[0.64477859 0.89641884 0.86355138 0.89418741 0.7422256 ]
  [0.05897595 0.53376983 0.67591669 0.81828168 0.57045207]
  [0.34571598 0.96314    0.38039216 0.50406145 0.12681685]
  [0.16103219 0.17502662 0.75465242 0.18050968 0.9861452 ]]

 [[0.25719552 0.52250463 0.85864575 0.62885899 0.93010446]
  [0.64419896 0.37639589 0.67292751 0.28252162 0.06294175]
  [0.66290859 0.01828023 0.47456788 0.09996702 0.44227327]
  [0.31678042 0.32316412 0.32628916 0.22990484 0.47024849]]

 [[0.60945809 0.85148652 0.24734991 0.852702   0.91857969]
  [0.61141536 0.2614762  0.6357038  0.74227369 0.09065509]
  [0.48025622 0.27108494 0.13860044 0.20101975 0.92120797]
  [0.47618347 0.01892212 0.74914416 0.18879969 0.99420585]]]


In [43]:
print(g[0,1]) # Second subgroup of the first group

[[0.25719552 0.52250463 0.85864575 0.62885899 0.93010446]
 [0.64419896 0.37639589 0.67292751 0.28252162 0.06294175]
 [0.66290859 0.01828023 0.47456788 0.09996702 0.44227327]
 [0.31678042 0.32316412 0.32628916 0.22990484 0.47024849]]


In [95]:
print(g[0,1,2]) # Third row of the second subgroup of the first group

[0.66290859 0.01828023 0.47456788 0.09996702 0.44227327]


In [97]:
print(g[0,1,:,3]) # Fourth column of the second subgroup of the first group

[0.62885899 0.28252162 0.09996702 0.22990484]


In [98]:
print(g[0,1,2,3]) # Value in the third row and fourth column of the second subgroup of the first group

0.09996701609633529


#### Modifying a slice will modify the array

In [16]:
a[0,0]

0.25863261343053734

In [17]:
a[0,0] = 0.5

In [18]:
print(a)

[[0.5        0.29037444 0.23045113]
 [0.6215434  0.88239921 0.08838296]
 [0.38117844 0.61508489 0.55940369]
 [0.73903451 0.02268816 0.42810847]
 [0.66516596 0.14152668 0.67917047]
 [0.4537806  0.43918452 0.03528909]]


#### Boolean indexing

In [52]:
bool_idx = (a > 0.7)
print(bool_idx)

[[False False False]
 [False  True False]
 [False False False]
 [ True False False]
 [False False False]
 [False False False]]


In [53]:
print(a[bool_idx])
print(a[a > 0.7]) # in a single expression

[0.88239921 0.73903451]
[0.88239921 0.73903451]



### Operations:

- np.sum

- np.mean

- Structure: np.sum(array[index], axis, dtype)
    - Axis: axis or axes along which the means are computed. The default is to compute the mean of the flattened array. 
        - Axis 0: Move down the rows (so you will compute the sum/mean of each column)
        - Axis 1: Move horizontally across the columns (so you will compute the sum/mean of each row)
    - Dtype: Type to use in computing the result. For integer inputs, the default is float64; for floating point inputs, it is the same as the input dtype.
    
    *axis and dtype are optional to input


    


Lists do not behave the same way: sum means concatenation

In [56]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [99]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y) 

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [100]:
print(np.add(x,y)) # Sum of arrays x and y

[[ 6  8]
 [10 12]]


In [92]:
print("array a \n", a, "\n")
print("array f \n", f, "\n")

# Mean of each column in matrix a
print("Mean of each column in matrix a")
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print("\n Mean of each row in matrix a")
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array f
print("\n Mean of all the elements in the first two groups of array f")
print(np.mean(f[:2]))

array a 
 [[0.5        0.29037444 0.23045113]
 [0.6215434  0.88239921 0.08838296]
 [0.38117844 0.61508489 0.55940369]
 [0.73903451 0.02268816 0.42810847]
 [0.66516596 0.14152668 0.67917047]
 [0.4537806  0.43918452 0.03528909]] 

array f 
 [[[0.89836095 0.29609629 0.80292778 0.29961626 0.17414411]
  [0.62615406 0.76274847 0.40216247 0.84071922 0.60798756]
  [0.32435899 0.64839192 0.09046267 0.49975624 0.26851702]
  [0.04010463 0.10691695 0.87779608 0.15565992 0.0731709 ]]

 [[0.98540219 0.91196259 0.52092403 0.11833242 0.94549908]
  [0.40834637 0.22072044 0.63192318 0.26842969 0.4405589 ]
  [0.33972738 0.58248482 0.31878545 0.04343898 0.69064977]
  [0.81670972 0.16207972 0.66557102 0.05874646 0.96241985]]

 [[0.35176515 0.04158829 0.07035751 0.9140906  0.39938913]
  [0.62886176 0.70798876 0.07269246 0.67608459 0.98425197]
  [0.7588117  0.97790797 0.79283338 0.05645006 0.47725166]
  [0.91680407 0.44627754 0.1927636  0.91201192 0.92346065]]] 

Mean of each column in matrix a
[0.56011715 0

### Transpose

In [93]:
print(x)

[[1 2]
 [3 4]]


In [94]:
print(x.T)

[[1 3]
 [2 4]]


### Broadcasting

np.tile

In [103]:
# We will add the vector v to each row of the matrix x, storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("array x \n", x)

v = np.array([1, 0, 1])
print("array v \n", v)

y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

array x 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array v 
 [1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [105]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [30]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [31]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


[how broadcasting works](https://numpy.org/doc/stable/user/basics.broadcasting.html)

Some applications of bradcasting:

In [32]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [33]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [34]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [35]:
x = c[0,0]

print("x", "\n", x)

y = c[0,1]
print("y", "\n", y)

x 
 1.0
y 
 1.0


In [36]:
# Add elements of x and y together
print(np.add(x, y))

2.0


In [37]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

0.0


In [38]:
# Multiply elements of x and y together
print(np.multiply(x, y))

1.0


In [39]:
# Divide elements of y by elements of x
print(np.divide(y, x))

1.0
